FROM centos:centos7
MAINTAINER WangLX<15201376500@163.com>

RUN yum install passwd openssl openssh-server curl iproute net-tools -y && yum clean all && rm -rf /var/cache/yum 

#生成密钥
RUN ssh-keygen -t rsa -f /etc/ssh/ssh_host_rsa_key \
    && ssh-keygen -t rsa -f /etc/ssh/ssh_host_ecdsa_key \
    && ssh-keygen -t rsa -f /etc/ssh/ssh_host_ed25519_key

#修改配置信息
RUN /bin/sed -i 's/.*session.*required.*pam_loginuid.so.*/session optional pam_loginuid.so/g' /etc/pam.d/sshd \
    && /bin/sed -i 's/UsePAM yes/UsePAM no/g' /etc/ssh/sshd_config \
    && /bin/sed -i "s/#UsePrivilegeSeparation.*/UsePrivilegeSeparation no/g" /etc/ssh/sshd_config \
    && /bin/sed -i "s/#Port 22/Port 2200/g" /etc/ssh/sshd_config \
    && /bin/echo "admin123" | passwd --stdin root

EXPOSE 2200

CMD ["/usr/sbin/sshd","-D"]
